// ---------------------------------------------------------------------------
// Gallery — hero promotion
//
// Floats the most visually arresting plates ("grand and stunning") to the
// front of each gallery's detail list while preserving the owner's curated
// narrative for everything below. Scores are AI-generated by
// `scripts/score-gallery-plates.mjs` and baked into
// `src/data/gallery/plate-scores.json`.
//
// Rules:
//   - Only plates with `wowScore >= MIN_WOW` get promoted.
//   - Cap promotions at `TOP_K` so we never blow up the curated arc.
//   - Promoted plates are ordered by `wowScore` desc, then by their original
//     index (stable for ties).
//   - If no scores are loaded for a gallery, return the array untouched.
// ---------------------------------------------------------------------------

import scoresJson from "@/data/gallery/plate-scores.json";
import type { GalleryImage } from "@/content/gallery-projects";

type PlateScore = { wow: number; product: number };
const SCORES = scoresJson as Record<string, PlateScore>;

const TOP_K = 4;
// Soft floor — promotions must beat a curated plate by a real margin OR
// clear an absolute "would stop a scroll" score.
const ABSOLUTE_WOW = 8;
const RELATIVE_MARGIN = 1.5;

/** Extract the storage path from a full public URL — keys in plate-scores.json. */
function keyFor(src: string): string {
  const marker = "/image-galleries/";
  const i = src.indexOf(marker);
  if (i === -1) return src;
  return decodeURIComponent(src.slice(i + marker.length));
}

export function promoteHeroes(
  images: readonly GalleryImage[],
  opts: { topK?: number } = {},
): GalleryImage[] {
  const topK = opts.topK ?? TOP_K;

  const scored = images.map((img, idx) => {
    const s = SCORES[keyFor(img.src)];
    return { img, idx, wow: s?.wow ?? 0, product: s?.product ?? 0 };
  });

  if (scored.every((s) => s.wow === 0)) return [...images];

  // Top of the field for THIS gallery. Require minimum product visibility so
  // we never promote pure portraits / candids over a styled scene.
  const ranked = [...scored]
    .filter((s) => s.product >= 3)
    .sort((a, b) => b.wow - a.wow || a.idx - b.idx);

  // Only promote plates that are meaningfully better than the curated lead.
  const leadScore = scored[0]?.wow ?? 0;
  const candidates = ranked
    .filter((s) => s.wow >= ABSOLUTE_WOW || s.wow >= leadScore + RELATIVE_MARGIN)
    .slice(0, topK);

  if (candidates.length === 0) return [...images];

  const promotedIdx = new Set(candidates.map((c) => c.idx));
  const rest = scored.filter((s) => !promotedIdx.has(s.idx)).map((s) => s.img);
  return [...candidates.map((c) => c.img), ...rest];
}

