// ---------------------------------------------------------------------------
// Gallery — hero promotion
//
// Floats the most visually arresting plates ("grand and stunning") to the
// front of each gallery's detail list while preserving the owner's curated
// narrative for everything below. Scores are AI-generated by
// `scripts/score-gallery-plates.mjs` and baked into
// `src/data/gallery/plate-scores.json`.
//
// Rules:
//   - Only plates with `wowScore >= MIN_WOW` get promoted.
//   - Cap promotions at `TOP_K` so we never blow up the curated arc.
//   - Promoted plates are ordered by `wowScore` desc, then by their original
//     index (stable for ties).
//   - If no scores are loaded for a gallery, return the array untouched.
// ---------------------------------------------------------------------------

import scoresJson from "@/data/gallery/plate-scores.json";
import type { GalleryImage } from "@/content/gallery-projects";

type PlateScore = { wow: number; product: number };
const SCORES = scoresJson as Record<string, PlateScore>;

const TOP_K = 4;
const MIN_WOW = 7.5;

/** Extract the storage path from a full public URL — keys in plate-scores.json. */
function keyFor(src: string): string {
  const marker = "/image-galleries/";
  const i = src.indexOf(marker);
  if (i === -1) return src;
  return decodeURIComponent(src.slice(i + marker.length));
}

export function promoteHeroes(
  images: readonly GalleryImage[],
  opts: { topK?: number; minWow?: number } = {},
): GalleryImage[] {
  const topK = opts.topK ?? TOP_K;
  const minWow = opts.minWow ?? MIN_WOW;

  const scored = images.map((img, idx) => {
    const s = SCORES[keyFor(img.src)];
    return { img, idx, wow: s?.wow ?? 0, product: s?.product ?? 0 };
  });

  // Candidates: scored plates clearing the wow bar, AI-confident on decor.
  const candidates = scored
    .filter((s) => s.wow >= minWow && s.product >= 2)
    .sort((a, b) => b.wow - a.wow || a.idx - b.idx)
    .slice(0, topK);

  if (candidates.length === 0) return [...images];

  const promotedIdx = new Set(candidates.map((c) => c.idx));
  const rest = scored.filter((s) => !promotedIdx.has(s.idx)).map((s) => s.img);
  return [...candidates.map((c) => c.img), ...rest];
}
