import { createClient } from '@supabase/supabase-js';
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const buf = Buffer.from('hello cache test ' + Date.now());
const path = `__cachetest/${Date.now()}.txt`;
const { error: e1 } = await sb.storage.from('missing-gaps').upload(path, buf, { contentType: 'text/plain', cacheControl: '31536000', upsert: true });
console.log('upload:', e1?.message || 'ok');
await new Promise(r => setTimeout(r, 1500));
const url = `${process.env.SUPABASE_URL}/storage/v1/object/public/missing-gaps/${path}`;
const r = await fetch(url);
console.log('status:', r.status, 'cache-control:', r.headers.get('cache-control'));
console.log('url:', url);
