import { createClient } from '@supabase/supabase-js';
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const path = 'JUNO Clear Glass Lamp.png';
const { data: blob } = await sb.storage.from('missing-gaps').download(path);
const buf = Buffer.from(await blob.arrayBuffer());
console.log('downloaded bytes:', buf.length);
const { error } = await sb.storage.from('missing-gaps').upload(path, buf, { contentType: 'image/png', cacheControl: '31536000', upsert: true });
console.log('upsert:', error?.message || 'ok');
await new Promise(r => setTimeout(r, 1500));
const r = await fetch(`${process.env.SUPABASE_URL}/storage/v1/object/public/missing-gaps/${encodeURIComponent(path)}?cb=${Date.now()}`);
console.log('status:', r.status, 'cache-control:', r.headers.get('cache-control'));
