-- Gallery dedup chunk 3/4
-- oxford-fossil-20-plinth-3893: 5 → 4
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/OXFORD 20 Plinth 1.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3893/51eabffcde12-OXFORD_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3893/e314caf545ff-OXFORD_26_Plinth_1.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3893/ff8fe53b7aa7-OXFORD_36_Plinth_1.png']::text[] WHERE rms_id = '3893';
-- oxford-fossil-26-plinth-3894: 5 → 4
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/OXFORD 26 Plinth 1.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3893/51eabffcde12-OXFORD_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3893/26ed893a36bd-OXFORD_20_Plinth_1.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3893/ff8fe53b7aa7-OXFORD_36_Plinth_1.png']::text[] WHERE rms_id = '3894';
-- oxford-fossil-36-plinth-3895: 5 → 4
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/OXFORD 36 Plinth 1.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3893/51eabffcde12-OXFORD_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3893/26ed893a36bd-OXFORD_20_Plinth_1.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3893/e314caf545ff-OXFORD_26_Plinth_1.png']::text[] WHERE rms_id = '3895';
-- quinn-antique-bone-butter-knife-3399: 9 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/55da8d592c08-QUINN_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Butter Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/8d0f80ec2ea9-QUINN_Dinner_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/db02b4810566-QUINN_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/267a7e07d920-QUINN_Dinner_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/52d1a2daf204-QUINN_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/e06e512f4ae0-QUINN_Dinner_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/11791b944e8e-QUINN_Steak_Knife.png']::text[] WHERE rms_id = '3399';
-- quinn-antique-bone-dinner-fork-3393: 11 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/55da8d592c08-QUINN_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Dinner Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Dinner Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Dinner Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/db02b4810566-QUINN_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/52d1a2daf204-QUINN_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/11791b944e8e-QUINN_Steak_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/fc405f17df06-QUINN_Butter_Knife.png']::text[] WHERE rms_id = '3393';
-- quinn-antique-bone-dinner-knife-3397: 11 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/55da8d592c08-QUINN_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Dinner Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Dinner Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Dinner Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/db02b4810566-QUINN_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/52d1a2daf204-QUINN_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/11791b944e8e-QUINN_Steak_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/fc405f17df06-QUINN_Butter_Knife.png']::text[] WHERE rms_id = '3397';
-- quinn-antique-bone-dinner-spoon-3395: 11 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/55da8d592c08-QUINN_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Dinner Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Dinner Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Dinner Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/db02b4810566-QUINN_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/52d1a2daf204-QUINN_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/11791b944e8e-QUINN_Steak_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/fc405f17df06-QUINN_Butter_Knife.png']::text[] WHERE rms_id = '3395';
-- quinn-antique-bone-salad-dessert-fork-3394: 9 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/55da8d592c08-QUINN_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Salad Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/8d0f80ec2ea9-QUINN_Dinner_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/267a7e07d920-QUINN_Dinner_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/52d1a2daf204-QUINN_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/e06e512f4ae0-QUINN_Dinner_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/11791b944e8e-QUINN_Steak_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/fc405f17df06-QUINN_Butter_Knife.png']::text[] WHERE rms_id = '3394';
-- quinn-antique-bone-steak-knife-3398: 9 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/55da8d592c08-QUINN_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Steak Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/8d0f80ec2ea9-QUINN_Dinner_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/db02b4810566-QUINN_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/267a7e07d920-QUINN_Dinner_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/52d1a2daf204-QUINN_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/e06e512f4ae0-QUINN_Dinner_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/fc405f17df06-QUINN_Butter_Knife.png']::text[] WHERE rms_id = '3398';
-- quinn-antique-bone-tea-dessert-spoon-3396: 9 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/55da8d592c08-QUINN_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/QUINN Tea Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/8d0f80ec2ea9-QUINN_Dinner_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/db02b4810566-QUINN_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/267a7e07d920-QUINN_Dinner_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/52d1a2daf204-QUINN_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/e06e512f4ae0-QUINN_Dinner_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3393/fc405f17df06-QUINN_Butter_Knife.png']::text[] WHERE rms_id = '3396';
-- raphael-blue-rectangle-bowl-2733: 3 → 2
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/SERVEWEAR/RAPHAEL Blue Bowl 1.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/2733/c5e1bf2afd28-RAPHAEL_Blue_Bowl.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/2733/dc46e07b1be7-RAPHAEL_Blue_Bowl_2.png']::text[] WHERE rms_id = '2733';
-- redford-light-fixed-cement-rect-bistro-2-1029: 3 → 2
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLES/REDFORD Cement Rect Bistro 2.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/1029/2018eb50c5fc-REDFORD_Cement_Rect_Bistro.png']::text[] WHERE rms_id = '1029';
-- redford-light-fixed-cement-rect-bistro-3-1030: 3 → 2
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLES/REDFORD Cement Rect Bistro 3.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/1029/2018eb50c5fc-REDFORD_Cement_Rect_Bistro.png']::text[] WHERE rms_id = '1030';