-- Gallery dedup chunk 2/4
-- elysia-10-ruffled-marble-bowl-3464: 3 → 2
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/ELYSIA Med Marble Bowl.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3465/fac072af9574-ELYSIA_Large_Marble_Bowl.png']::text[] WHERE rms_id = '3464';
-- elysia-14-ruffled-marble-bowl-3465: 3 → 2
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/ELYSIA Large Marble Bowl.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3464/314a3816121d-ELYSIA_Med_Marble_Bowl.png']::text[] WHERE rms_id = '3465';
-- estella-copper-stainless-dinner-fork-3414: 4 → 3
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/_family-sets/ESTELLA/ESTELLA%2BSet.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/ESTELLA Dinner Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/ESTELLA Dinner Knife.png']::text[] WHERE rms_id = '3414';
-- estella-copper-stainless-dinner-knife-3418: 4 → 3
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/_family-sets/ESTELLA/ESTELLA%2BSet.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/ESTELLA Dinner Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/ESTELLA Dinner Fork.png']::text[] WHERE rms_id = '3418';
-- estella-copper-stainless-dinner-spoon-3416: 4 → 3
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/_family-sets/ESTELLA/ESTELLA%2BSet.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/ESTELLA Dinner Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/ESTELLA Dinner Fork.png']::text[] WHERE rms_id = '3416';
-- evelda-7-ceramic-chain-vase-4026: 4 → 3
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/EVELDA 7 Chain Vase.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4025/eb4d584f540b-EVELDA_Duo.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4025/5d7f9bbcbd1f-EVELDA_9.5_Chain_Vase.png']::text[] WHERE rms_id = '4026';
-- evelda-9-5-ceramic-chain-vase-4025: 4 → 3
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/EVELDA 9.5 Chain Vase.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4025/eb4d584f540b-EVELDA_Duo.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4025/74e4e60ffab1-EVELDA_7_Chain_Vase.png']::text[] WHERE rms_id = '4025';
-- jina-14-black-metal-vase-4020: 4 → 3
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/JINA Tall Black Metal Vase.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4020/6445288ff4b3-JINA_Duo.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4020/084af8329792-JINA_Short_Black_Metal_Vase.png']::text[] WHERE rms_id = '4020';
-- jina-7-5-black-metal-vase-4021: 4 → 3
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/JINA Short Black Metal Vase.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4020/6445288ff4b3-JINA_Duo.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4020/944dc5eda9e2-JINA_Tall_Black_Metal_Vase.png']::text[] WHERE rms_id = '4021';
-- monroe-black-slat-tambour-double-10-4118: 3 → 2
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/BARS/MONROE%20Black%20Slat%20Double%2010.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4108/aa9745f2c6bb-MONROE_Black_Slat_Single_8_27.png']::text[] WHERE rms_id = '4118';
-- monroe-black-slat-tambour-double-16-4117: 3 → 2
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/BARS/MONROE%20Black%20Slat%20Double%2016.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4108/aa9745f2c6bb-MONROE_Black_Slat_Single_8_27.png']::text[] WHERE rms_id = '4117';
-- monroe-black-slat-tambour-single-8-4108: 3 → 2
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/BARS/MONROE%20Black%20Slat%20Single%208.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4117/9523ed120e8f-MONROE_Black_Slat_Double_16_27.png']::text[] WHERE rms_id = '4108';