-- Gallery dedup chunk 4/4
-- sinatra-walnut-fluted-bar-double-16-4067: 3 → 2
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/BARS/SINATRA%20Walnut%20Fluted%20-%20Double%2016.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4064/df1e6c014bed-SINATRA_Walnut_Fluted_-_Single_8_27.png']::text[] WHERE rms_id = '4067';
-- sinatra-walnut-fluted-bar-single-8-4064: 3 → 2
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/BARS/SINATRA%20Walnut%20Fluted%20-%20Single%208.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4064/cd3d51467714-SINATRA_Walnut_Fluted_-_Double_16_27.png']::text[] WHERE rms_id = '4064';
-- tirzah-6-asymmetrical-vase-4017: 5 → 3
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/TIRZAH Vase Small.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/TIRZAH Vase Large.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4016/8f0a21079578-TIRZAH_Duo.png']::text[] WHERE rms_id = '4017';
-- tirzah-8-asymmetrical-vase-4016: 5 → 3
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/TIRZAH Vase Large.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/STYLING/TIRZAH Vase Small.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/4016/8f0a21079578-TIRZAH_Duo.png']::text[] WHERE rms_id = '4016';
-- winslow-tortoise-bistro-butter-knife-3413: 9 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/c121512ae4da-WINSLOW_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Butter Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/37ff2b303171-WINSLOW_Dinner_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/7d92dfc513e8-WINSLOW_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/b9707ee521ba-WINSLOW_Dinner_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/79ad9a6c7868-WINSLOW_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/3a9ca24b1734-WINSLOW_Dinner_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/009639a702bc-WINSLOW_Steak_Knife.png']::text[] WHERE rms_id = '3413';
-- winslow-tortoise-bistro-dinner-fork-3407: 11 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/c121512ae4da-WINSLOW_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Dinner Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Dinner Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Dinner Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/7d92dfc513e8-WINSLOW_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/79ad9a6c7868-WINSLOW_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/009639a702bc-WINSLOW_Steak_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/21a01c680e9f-WINSLOW_Butter_Knife.png']::text[] WHERE rms_id = '3407';
-- winslow-tortoise-bistro-dinner-knife-3411: 11 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/c121512ae4da-WINSLOW_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Dinner Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Dinner Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Dinner Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/7d92dfc513e8-WINSLOW_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/79ad9a6c7868-WINSLOW_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/009639a702bc-WINSLOW_Steak_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/21a01c680e9f-WINSLOW_Butter_Knife.png']::text[] WHERE rms_id = '3411';
-- winslow-tortoise-bistro-dinner-spoon-3409: 11 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/c121512ae4da-WINSLOW_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Dinner Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Dinner Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Dinner Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/7d92dfc513e8-WINSLOW_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/79ad9a6c7868-WINSLOW_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/009639a702bc-WINSLOW_Steak_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/21a01c680e9f-WINSLOW_Butter_Knife.png']::text[] WHERE rms_id = '3409';
-- winslow-tortoise-bistro-salad-dessert-fork-3408: 9 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/c121512ae4da-WINSLOW_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Salad Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/37ff2b303171-WINSLOW_Dinner_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/b9707ee521ba-WINSLOW_Dinner_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/79ad9a6c7868-WINSLOW_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/3a9ca24b1734-WINSLOW_Dinner_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/009639a702bc-WINSLOW_Steak_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/21a01c680e9f-WINSLOW_Butter_Knife.png']::text[] WHERE rms_id = '3408';
-- winslow-tortoise-bistro-steak-knife-3412: 9 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/c121512ae4da-WINSLOW_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Steak Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/37ff2b303171-WINSLOW_Dinner_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/7d92dfc513e8-WINSLOW_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/b9707ee521ba-WINSLOW_Dinner_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/79ad9a6c7868-WINSLOW_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/3a9ca24b1734-WINSLOW_Dinner_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/21a01c680e9f-WINSLOW_Butter_Knife.png']::text[] WHERE rms_id = '3412';
-- winslow-tortoise-bistro-tea-dessert-spoon-3410: 9 → 8
UPDATE public.inventory_items SET images = ARRAY['https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/c121512ae4da-WINSLOW_Set.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/inventory/inventory/TABLEWEAR/WINSLOW Tea Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/37ff2b303171-WINSLOW_Dinner_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/7d92dfc513e8-WINSLOW_Salad_Fork.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/b9707ee521ba-WINSLOW_Dinner_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/79ad9a6c7868-WINSLOW_Tea_Spoon.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/3a9ca24b1734-WINSLOW_Dinner_Knife.png', 'https://wdyfavzfquegrxklcpmq.supabase.co/storage/v1/object/public/squarespace-mirror/squarespace/3407/21a01c680e9f-WINSLOW_Butter_Knife.png']::text[] WHERE rms_id = '3412';